#!/usr/bin/env bash
#  Script bach FizzBuzz
conter=1
while [ $conter -le 100 ];
do
if [ $((conter%3)) == 0 -a $((conter%5)) == 0 ]
then
    echo "FizzBuzz"
elif [ $((conter%3)) == 0 ]
then
    echo "Fizz"
elif [ $((conter%5)) == 0 ]
then
    echo "Buzz"
else
    echo $conter
fi
    let conter=conter+1
done
