#!/usr/bin/env bash
#  Script bash that displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ];
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ];
    do
echo  $minutes
let minutes=minutes+1
    done
    let hour=hour+1
done
