#!/usr/bin/env bash
#  Script bash gives you information about the holbertonschool file
if [ -e holbertonschool ]
then
    echo "holbertonschool file exists"
    if [ -s holbertonschool ]
    then
echo "holbertonschool file is not empty"
    else
echo "holbertonschool file is empty"
    fi
    if [ -f holbertonschool ]
    then
echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi